# Generated by Django 4.1.7 on 2023-04-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redmark_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="scores",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="taken",
            field=models.BooleanField(default=False),
        ),
    ]
