# Generated by Django 4.1.7 on 2023-04-06 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("redmark_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_answer",
                to="redmark_app.answer",
            ),
        ),
    ]
