# Generated by Django 4.1.7 on 2023-04-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redmark_app", "0002_userprofile_scores_userprofile_taken"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
